services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
